import re


def detect_ai(text: str) -> str:
    """
    Determines if a given string was likely generated by AI based on three structural rules.

    Args:
        text: The input string (one or more sentences).

    Returns:
        "AI" if any rule is met, otherwise "Human".
    """

    # -------------------------------------------------------------------------
    # Rule 1: It contains two or more dashes (-)
    if text.count('-') >= 2:
        return "AI"

    # -------------------------------------------------------------------------
    # Rule 2: It contains two or more sets of parenthesis (()).
    if text.count('(') >= 2 and text.count(')') >= 2:
        return "AI"

    # -------------------------------------------------------------------------
    # Rule 3: It contains three or more words with 7 or more letters.
    long_word_count = 0

    # 1. Clean the text: Replace any non-letter characters (like periods, commas, etc.)
    # with a space. This ensures accurate word separation and length counting.
    # Example: "word." becomes "word "
    cleaned_text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # 2. Split the cleaned text into words and iterate.
    # .split() handles multiple spaces created during cleaning by skipping empty strings.
    for word in cleaned_text.split():
        # Check if the word length (using only letters) is 7 or more.
        if len(word) >= 7:
            long_word_count += 1

    # Check if the long word threshold is met.
    if long_word_count >= 3:
        return "AI"

    # If none of the AI detection rules were triggered, return "Human".
    return "Human"


# --- Testing the Enhanced Solution ---

print("The quick brown fox jumped over the lazy dog.:", detect_ai("The quick brown fox jumped over the lazy dog."))
print("The hypersonic brown fox - jumped (over) the lazy dog.:",
      detect_ai("The hypersonic brown fox - jumped (over) the lazy dog."))
print("Yes - you're right! I made a mistake there - let me try again.:",
      detect_ai("Yes - you're right! I made a mistake there - let me try again."))  # AI (2 dashes)
print("The extraordinary students were studying vivaciously.:", detect_ai(
    "The extraordinary students were studying vivaciously."))  # AI (extraordinary, students, studying, vivaciously = 4 words)
print("The (excited) student was (coding) in the library.:", detect_ai(
    "The (excited) student was (coding) in the library."))  # Human (Only 1 set of parentheses, 2 long words)
print("The (incredibly) exciting (project) launched successfully (today).",
      detect_ai("The (incredibly) exciting (project) launched successfully (today)."))  # AI (3 sets of parentheses)